namespace CabManagement
{
    partial class cab
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(cab));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.QD_Panel = new System.Windows.Forms.Panel();
            this.bun_addcabppkm_tb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bun_addcabdet_tb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bun_addcabnam_tb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bun_addcabno_tb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.list_btn_qd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.Delete_btn_qd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.modify_btn_qd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.Save_btn_qd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.new_btn_qd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bun_addcab_dgv = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.add_cabno = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.add_cabmod = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.add_cabdet = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.add_cabppkm = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.QD_Panel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bun_addcab_dgv)).BeginInit();
            this.SuspendLayout();
            // 
            // QD_Panel
            // 
            this.QD_Panel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(20)))), ((int)(((byte)(28)))));
            this.QD_Panel.Controls.Add(this.bun_addcabppkm_tb);
            this.QD_Panel.Controls.Add(this.bun_addcabdet_tb);
            this.QD_Panel.Controls.Add(this.bun_addcabnam_tb);
            this.QD_Panel.Controls.Add(this.bun_addcabno_tb);
            this.QD_Panel.Controls.Add(this.label5);
            this.QD_Panel.Controls.Add(this.label4);
            this.QD_Panel.Controls.Add(this.label1);
            this.QD_Panel.Controls.Add(this.label3);
            this.QD_Panel.Controls.Add(this.label2);
            this.QD_Panel.Controls.Add(this.list_btn_qd);
            this.QD_Panel.Controls.Add(this.Delete_btn_qd);
            this.QD_Panel.Controls.Add(this.modify_btn_qd);
            this.QD_Panel.Controls.Add(this.Save_btn_qd);
            this.QD_Panel.Controls.Add(this.new_btn_qd);
            this.QD_Panel.Controls.Add(this.bun_addcab_dgv);
            this.QD_Panel.Location = new System.Drawing.Point(22, 22);
            this.QD_Panel.Name = "QD_Panel";
            this.QD_Panel.Size = new System.Drawing.Size(1397, 848);
            this.QD_Panel.TabIndex = 9;
            // 
            // bun_addcabppkm_tb
            // 
            this.bun_addcabppkm_tb.AcceptsReturn = false;
            this.bun_addcabppkm_tb.AcceptsTab = false;
            this.bun_addcabppkm_tb.AnimationSpeed = 200;
            this.bun_addcabppkm_tb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bun_addcabppkm_tb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bun_addcabppkm_tb.AutoSizeHeight = true;
            this.bun_addcabppkm_tb.BackColor = System.Drawing.Color.Transparent;
            this.bun_addcabppkm_tb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bun_addcabppkm_tb.BackgroundImage")));
            this.bun_addcabppkm_tb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bun_addcabppkm_tb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bun_addcabppkm_tb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bun_addcabppkm_tb.BorderColorIdle = System.Drawing.Color.Silver;
            this.bun_addcabppkm_tb.BorderRadius = 1;
            this.bun_addcabppkm_tb.BorderThickness = 1;
            this.bun_addcabppkm_tb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bun_addcabppkm_tb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_addcabppkm_tb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bun_addcabppkm_tb.DefaultText = "";
            this.bun_addcabppkm_tb.FillColor = System.Drawing.Color.White;
            this.bun_addcabppkm_tb.HideSelection = true;
            this.bun_addcabppkm_tb.IconLeft = null;
            this.bun_addcabppkm_tb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_addcabppkm_tb.IconPadding = 10;
            this.bun_addcabppkm_tb.IconRight = null;
            this.bun_addcabppkm_tb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_addcabppkm_tb.Lines = new string[0];
            this.bun_addcabppkm_tb.Location = new System.Drawing.Point(195, 344);
            this.bun_addcabppkm_tb.MaxLength = 32767;
            this.bun_addcabppkm_tb.MinimumSize = new System.Drawing.Size(1, 1);
            this.bun_addcabppkm_tb.Modified = false;
            this.bun_addcabppkm_tb.Multiline = false;
            this.bun_addcabppkm_tb.Name = "bun_addcabppkm_tb";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_addcabppkm_tb.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bun_addcabppkm_tb.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_addcabppkm_tb.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_addcabppkm_tb.OnIdleState = stateProperties4;
            this.bun_addcabppkm_tb.Padding = new System.Windows.Forms.Padding(3);
            this.bun_addcabppkm_tb.PasswordChar = '\0';
            this.bun_addcabppkm_tb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bun_addcabppkm_tb.PlaceholderText = "Enter text";
            this.bun_addcabppkm_tb.ReadOnly = false;
            this.bun_addcabppkm_tb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bun_addcabppkm_tb.SelectedText = "";
            this.bun_addcabppkm_tb.SelectionLength = 0;
            this.bun_addcabppkm_tb.SelectionStart = 0;
            this.bun_addcabppkm_tb.ShortcutsEnabled = true;
            this.bun_addcabppkm_tb.Size = new System.Drawing.Size(318, 34);
            this.bun_addcabppkm_tb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bun_addcabppkm_tb.TabIndex = 27;
            this.bun_addcabppkm_tb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bun_addcabppkm_tb.TextMarginBottom = 0;
            this.bun_addcabppkm_tb.TextMarginLeft = 3;
            this.bun_addcabppkm_tb.TextMarginTop = 1;
            this.bun_addcabppkm_tb.TextPlaceholder = "Enter text";
            this.bun_addcabppkm_tb.UseSystemPasswordChar = false;
            this.bun_addcabppkm_tb.WordWrap = true;
            this.bun_addcabppkm_tb.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.bun_addcabppkm_tb_KeyPress);
            // 
            // bun_addcabdet_tb
            // 
            this.bun_addcabdet_tb.AcceptsReturn = false;
            this.bun_addcabdet_tb.AcceptsTab = false;
            this.bun_addcabdet_tb.AnimationSpeed = 200;
            this.bun_addcabdet_tb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bun_addcabdet_tb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bun_addcabdet_tb.AutoSizeHeight = true;
            this.bun_addcabdet_tb.BackColor = System.Drawing.Color.Transparent;
            this.bun_addcabdet_tb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bun_addcabdet_tb.BackgroundImage")));
            this.bun_addcabdet_tb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bun_addcabdet_tb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bun_addcabdet_tb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bun_addcabdet_tb.BorderColorIdle = System.Drawing.Color.Silver;
            this.bun_addcabdet_tb.BorderRadius = 1;
            this.bun_addcabdet_tb.BorderThickness = 1;
            this.bun_addcabdet_tb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bun_addcabdet_tb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_addcabdet_tb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bun_addcabdet_tb.DefaultText = "";
            this.bun_addcabdet_tb.FillColor = System.Drawing.Color.White;
            this.bun_addcabdet_tb.HideSelection = true;
            this.bun_addcabdet_tb.IconLeft = null;
            this.bun_addcabdet_tb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_addcabdet_tb.IconPadding = 10;
            this.bun_addcabdet_tb.IconRight = null;
            this.bun_addcabdet_tb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_addcabdet_tb.Lines = new string[0];
            this.bun_addcabdet_tb.Location = new System.Drawing.Point(195, 236);
            this.bun_addcabdet_tb.MaxLength = 32767;
            this.bun_addcabdet_tb.MinimumSize = new System.Drawing.Size(1, 1);
            this.bun_addcabdet_tb.Modified = false;
            this.bun_addcabdet_tb.Multiline = false;
            this.bun_addcabdet_tb.Name = "bun_addcabdet_tb";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_addcabdet_tb.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bun_addcabdet_tb.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_addcabdet_tb.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_addcabdet_tb.OnIdleState = stateProperties8;
            this.bun_addcabdet_tb.Padding = new System.Windows.Forms.Padding(3);
            this.bun_addcabdet_tb.PasswordChar = '\0';
            this.bun_addcabdet_tb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bun_addcabdet_tb.PlaceholderText = "Enter text";
            this.bun_addcabdet_tb.ReadOnly = false;
            this.bun_addcabdet_tb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bun_addcabdet_tb.SelectedText = "";
            this.bun_addcabdet_tb.SelectionLength = 0;
            this.bun_addcabdet_tb.SelectionStart = 0;
            this.bun_addcabdet_tb.ShortcutsEnabled = true;
            this.bun_addcabdet_tb.Size = new System.Drawing.Size(318, 73);
            this.bun_addcabdet_tb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bun_addcabdet_tb.TabIndex = 26;
            this.bun_addcabdet_tb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bun_addcabdet_tb.TextMarginBottom = 0;
            this.bun_addcabdet_tb.TextMarginLeft = 3;
            this.bun_addcabdet_tb.TextMarginTop = 1;
            this.bun_addcabdet_tb.TextPlaceholder = "Enter text";
            this.bun_addcabdet_tb.UseSystemPasswordChar = false;
            this.bun_addcabdet_tb.WordWrap = true;
            // 
            // bun_addcabnam_tb
            // 
            this.bun_addcabnam_tb.AcceptsReturn = false;
            this.bun_addcabnam_tb.AcceptsTab = false;
            this.bun_addcabnam_tb.AnimationSpeed = 200;
            this.bun_addcabnam_tb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bun_addcabnam_tb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bun_addcabnam_tb.AutoSizeHeight = true;
            this.bun_addcabnam_tb.BackColor = System.Drawing.Color.Transparent;
            this.bun_addcabnam_tb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bun_addcabnam_tb.BackgroundImage")));
            this.bun_addcabnam_tb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bun_addcabnam_tb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bun_addcabnam_tb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bun_addcabnam_tb.BorderColorIdle = System.Drawing.Color.Silver;
            this.bun_addcabnam_tb.BorderRadius = 1;
            this.bun_addcabnam_tb.BorderThickness = 1;
            this.bun_addcabnam_tb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bun_addcabnam_tb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_addcabnam_tb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bun_addcabnam_tb.DefaultText = "";
            this.bun_addcabnam_tb.FillColor = System.Drawing.Color.White;
            this.bun_addcabnam_tb.HideSelection = true;
            this.bun_addcabnam_tb.IconLeft = null;
            this.bun_addcabnam_tb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_addcabnam_tb.IconPadding = 10;
            this.bun_addcabnam_tb.IconRight = null;
            this.bun_addcabnam_tb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_addcabnam_tb.Lines = new string[0];
            this.bun_addcabnam_tb.Location = new System.Drawing.Point(195, 167);
            this.bun_addcabnam_tb.MaxLength = 32767;
            this.bun_addcabnam_tb.MinimumSize = new System.Drawing.Size(1, 1);
            this.bun_addcabnam_tb.Modified = false;
            this.bun_addcabnam_tb.Multiline = false;
            this.bun_addcabnam_tb.Name = "bun_addcabnam_tb";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_addcabnam_tb.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bun_addcabnam_tb.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_addcabnam_tb.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_addcabnam_tb.OnIdleState = stateProperties12;
            this.bun_addcabnam_tb.Padding = new System.Windows.Forms.Padding(3);
            this.bun_addcabnam_tb.PasswordChar = '\0';
            this.bun_addcabnam_tb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bun_addcabnam_tb.PlaceholderText = "Enter text";
            this.bun_addcabnam_tb.ReadOnly = false;
            this.bun_addcabnam_tb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bun_addcabnam_tb.SelectedText = "";
            this.bun_addcabnam_tb.SelectionLength = 0;
            this.bun_addcabnam_tb.SelectionStart = 0;
            this.bun_addcabnam_tb.ShortcutsEnabled = true;
            this.bun_addcabnam_tb.Size = new System.Drawing.Size(318, 26);
            this.bun_addcabnam_tb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bun_addcabnam_tb.TabIndex = 25;
            this.bun_addcabnam_tb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bun_addcabnam_tb.TextMarginBottom = 0;
            this.bun_addcabnam_tb.TextMarginLeft = 3;
            this.bun_addcabnam_tb.TextMarginTop = 1;
            this.bun_addcabnam_tb.TextPlaceholder = "Enter text";
            this.bun_addcabnam_tb.UseSystemPasswordChar = false;
            this.bun_addcabnam_tb.WordWrap = true;
            // 
            // bun_addcabno_tb
            // 
            this.bun_addcabno_tb.AcceptsReturn = false;
            this.bun_addcabno_tb.AcceptsTab = false;
            this.bun_addcabno_tb.AnimationSpeed = 200;
            this.bun_addcabno_tb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bun_addcabno_tb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bun_addcabno_tb.AutoSizeHeight = true;
            this.bun_addcabno_tb.BackColor = System.Drawing.Color.Transparent;
            this.bun_addcabno_tb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bun_addcabno_tb.BackgroundImage")));
            this.bun_addcabno_tb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bun_addcabno_tb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bun_addcabno_tb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bun_addcabno_tb.BorderColorIdle = System.Drawing.Color.Silver;
            this.bun_addcabno_tb.BorderRadius = 1;
            this.bun_addcabno_tb.BorderThickness = 1;
            this.bun_addcabno_tb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bun_addcabno_tb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_addcabno_tb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bun_addcabno_tb.DefaultText = "";
            this.bun_addcabno_tb.FillColor = System.Drawing.Color.White;
            this.bun_addcabno_tb.HideSelection = true;
            this.bun_addcabno_tb.IconLeft = null;
            this.bun_addcabno_tb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_addcabno_tb.IconPadding = 10;
            this.bun_addcabno_tb.IconRight = null;
            this.bun_addcabno_tb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_addcabno_tb.Lines = new string[0];
            this.bun_addcabno_tb.Location = new System.Drawing.Point(195, 102);
            this.bun_addcabno_tb.MaxLength = 15;
            this.bun_addcabno_tb.MinimumSize = new System.Drawing.Size(1, 1);
            this.bun_addcabno_tb.Modified = false;
            this.bun_addcabno_tb.Multiline = false;
            this.bun_addcabno_tb.Name = "bun_addcabno_tb";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_addcabno_tb.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bun_addcabno_tb.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_addcabno_tb.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_addcabno_tb.OnIdleState = stateProperties16;
            this.bun_addcabno_tb.Padding = new System.Windows.Forms.Padding(3);
            this.bun_addcabno_tb.PasswordChar = '\0';
            this.bun_addcabno_tb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bun_addcabno_tb.PlaceholderText = "Enter text";
            this.bun_addcabno_tb.ReadOnly = false;
            this.bun_addcabno_tb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bun_addcabno_tb.SelectedText = "";
            this.bun_addcabno_tb.SelectionLength = 0;
            this.bun_addcabno_tb.SelectionStart = 0;
            this.bun_addcabno_tb.ShortcutsEnabled = true;
            this.bun_addcabno_tb.Size = new System.Drawing.Size(318, 26);
            this.bun_addcabno_tb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bun_addcabno_tb.TabIndex = 24;
            this.bun_addcabno_tb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bun_addcabno_tb.TextMarginBottom = 0;
            this.bun_addcabno_tb.TextMarginLeft = 3;
            this.bun_addcabno_tb.TextMarginTop = 1;
            this.bun_addcabno_tb.TextPlaceholder = "Enter text";
            this.bun_addcabno_tb.UseSystemPasswordChar = false;
            this.bun_addcabno_tb.WordWrap = true;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(37, 349);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(130, 22);
            this.label5.TabIndex = 18;
            this.label5.Text = "Price per k/m";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(36, 236);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(115, 22);
            this.label4.TabIndex = 17;
            this.label4.Text = "Cab Details";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(24, 167);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(167, 22);
            this.label1.TabIndex = 16;
            this.label1.Text = "Make and Model";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(24, 102);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(122, 22);
            this.label3.TabIndex = 15;
            this.label3.Text = "Cab Reg no";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Century Gothic", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(269, 20);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(152, 30);
            this.label2.TabIndex = 14;
            this.label2.Text = "Cab Details";
            // 
            // list_btn_qd
            // 
            this.list_btn_qd.AllowAnimations = true;
            this.list_btn_qd.AllowMouseEffects = true;
            this.list_btn_qd.AllowToggling = false;
            this.list_btn_qd.AnimationSpeed = 200;
            this.list_btn_qd.AutoGenerateColors = false;
            this.list_btn_qd.AutoRoundBorders = false;
            this.list_btn_qd.AutoSizeLeftIcon = true;
            this.list_btn_qd.AutoSizeRightIcon = true;
            this.list_btn_qd.BackColor = System.Drawing.Color.Transparent;
            this.list_btn_qd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.list_btn_qd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("list_btn_qd.BackgroundImage")));
            this.list_btn_qd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.list_btn_qd.ButtonText = "List";
            this.list_btn_qd.ButtonTextMarginLeft = 0;
            this.list_btn_qd.ColorContrastOnClick = 45;
            this.list_btn_qd.ColorContrastOnHover = 45;
            this.list_btn_qd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.list_btn_qd.CustomizableEdges = borderEdges1;
            this.list_btn_qd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.list_btn_qd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.list_btn_qd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.list_btn_qd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.list_btn_qd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.list_btn_qd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.list_btn_qd.ForeColor = System.Drawing.Color.White;
            this.list_btn_qd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.list_btn_qd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.list_btn_qd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.list_btn_qd.IconMarginLeft = 11;
            this.list_btn_qd.IconPadding = 10;
            this.list_btn_qd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.list_btn_qd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.list_btn_qd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.list_btn_qd.IconSize = 25;
            this.list_btn_qd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.list_btn_qd.IdleBorderRadius = 1;
            this.list_btn_qd.IdleBorderThickness = 1;
            this.list_btn_qd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.list_btn_qd.IdleIconLeftImage = null;
            this.list_btn_qd.IdleIconRightImage = null;
            this.list_btn_qd.IndicateFocus = false;
            this.list_btn_qd.Location = new System.Drawing.Point(529, 653);
            this.list_btn_qd.Name = "list_btn_qd";
            this.list_btn_qd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.list_btn_qd.OnDisabledState.BorderRadius = 1;
            this.list_btn_qd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.list_btn_qd.OnDisabledState.BorderThickness = 1;
            this.list_btn_qd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.list_btn_qd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.list_btn_qd.OnDisabledState.IconLeftImage = null;
            this.list_btn_qd.OnDisabledState.IconRightImage = null;
            this.list_btn_qd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.list_btn_qd.onHoverState.BorderRadius = 1;
            this.list_btn_qd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.list_btn_qd.onHoverState.BorderThickness = 1;
            this.list_btn_qd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.list_btn_qd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.list_btn_qd.onHoverState.IconLeftImage = null;
            this.list_btn_qd.onHoverState.IconRightImage = null;
            this.list_btn_qd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.list_btn_qd.OnIdleState.BorderRadius = 1;
            this.list_btn_qd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.list_btn_qd.OnIdleState.BorderThickness = 1;
            this.list_btn_qd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.list_btn_qd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.list_btn_qd.OnIdleState.IconLeftImage = null;
            this.list_btn_qd.OnIdleState.IconRightImage = null;
            this.list_btn_qd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.list_btn_qd.OnPressedState.BorderRadius = 1;
            this.list_btn_qd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.list_btn_qd.OnPressedState.BorderThickness = 1;
            this.list_btn_qd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.list_btn_qd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.list_btn_qd.OnPressedState.IconLeftImage = null;
            this.list_btn_qd.OnPressedState.IconRightImage = null;
            this.list_btn_qd.Size = new System.Drawing.Size(159, 39);
            this.list_btn_qd.TabIndex = 11;
            this.list_btn_qd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.list_btn_qd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.list_btn_qd.TextMarginLeft = 0;
            this.list_btn_qd.TextPadding = new System.Windows.Forms.Padding(0);
            this.list_btn_qd.UseDefaultRadiusAndThickness = true;
            this.list_btn_qd.Click += new System.EventHandler(this.list_btn_qd_Click);
            // 
            // Delete_btn_qd
            // 
            this.Delete_btn_qd.AllowAnimations = true;
            this.Delete_btn_qd.AllowMouseEffects = true;
            this.Delete_btn_qd.AllowToggling = false;
            this.Delete_btn_qd.AnimationSpeed = 200;
            this.Delete_btn_qd.AutoGenerateColors = false;
            this.Delete_btn_qd.AutoRoundBorders = false;
            this.Delete_btn_qd.AutoSizeLeftIcon = true;
            this.Delete_btn_qd.AutoSizeRightIcon = true;
            this.Delete_btn_qd.BackColor = System.Drawing.Color.Transparent;
            this.Delete_btn_qd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.Delete_btn_qd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Delete_btn_qd.BackgroundImage")));
            this.Delete_btn_qd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Delete_btn_qd.ButtonText = "Delete";
            this.Delete_btn_qd.ButtonTextMarginLeft = 0;
            this.Delete_btn_qd.ColorContrastOnClick = 45;
            this.Delete_btn_qd.ColorContrastOnHover = 45;
            this.Delete_btn_qd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Delete_btn_qd.CustomizableEdges = borderEdges2;
            this.Delete_btn_qd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Delete_btn_qd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Delete_btn_qd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Delete_btn_qd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Delete_btn_qd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.Delete_btn_qd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Delete_btn_qd.ForeColor = System.Drawing.Color.White;
            this.Delete_btn_qd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Delete_btn_qd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Delete_btn_qd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Delete_btn_qd.IconMarginLeft = 11;
            this.Delete_btn_qd.IconPadding = 10;
            this.Delete_btn_qd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Delete_btn_qd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Delete_btn_qd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Delete_btn_qd.IconSize = 25;
            this.Delete_btn_qd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.Delete_btn_qd.IdleBorderRadius = 1;
            this.Delete_btn_qd.IdleBorderThickness = 1;
            this.Delete_btn_qd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.Delete_btn_qd.IdleIconLeftImage = null;
            this.Delete_btn_qd.IdleIconRightImage = null;
            this.Delete_btn_qd.IndicateFocus = false;
            this.Delete_btn_qd.Location = new System.Drawing.Point(529, 593);
            this.Delete_btn_qd.Name = "Delete_btn_qd";
            this.Delete_btn_qd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Delete_btn_qd.OnDisabledState.BorderRadius = 1;
            this.Delete_btn_qd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Delete_btn_qd.OnDisabledState.BorderThickness = 1;
            this.Delete_btn_qd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Delete_btn_qd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Delete_btn_qd.OnDisabledState.IconLeftImage = null;
            this.Delete_btn_qd.OnDisabledState.IconRightImage = null;
            this.Delete_btn_qd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Delete_btn_qd.onHoverState.BorderRadius = 1;
            this.Delete_btn_qd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Delete_btn_qd.onHoverState.BorderThickness = 1;
            this.Delete_btn_qd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Delete_btn_qd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Delete_btn_qd.onHoverState.IconLeftImage = null;
            this.Delete_btn_qd.onHoverState.IconRightImage = null;
            this.Delete_btn_qd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Delete_btn_qd.OnIdleState.BorderRadius = 1;
            this.Delete_btn_qd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Delete_btn_qd.OnIdleState.BorderThickness = 1;
            this.Delete_btn_qd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.Delete_btn_qd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Delete_btn_qd.OnIdleState.IconLeftImage = null;
            this.Delete_btn_qd.OnIdleState.IconRightImage = null;
            this.Delete_btn_qd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Delete_btn_qd.OnPressedState.BorderRadius = 1;
            this.Delete_btn_qd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Delete_btn_qd.OnPressedState.BorderThickness = 1;
            this.Delete_btn_qd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Delete_btn_qd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Delete_btn_qd.OnPressedState.IconLeftImage = null;
            this.Delete_btn_qd.OnPressedState.IconRightImage = null;
            this.Delete_btn_qd.Size = new System.Drawing.Size(159, 39);
            this.Delete_btn_qd.TabIndex = 10;
            this.Delete_btn_qd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Delete_btn_qd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Delete_btn_qd.TextMarginLeft = 0;
            this.Delete_btn_qd.TextPadding = new System.Windows.Forms.Padding(0);
            this.Delete_btn_qd.UseDefaultRadiusAndThickness = true;
            this.Delete_btn_qd.Click += new System.EventHandler(this.Delete_btn_qd_Click);
            // 
            // modify_btn_qd
            // 
            this.modify_btn_qd.AllowAnimations = true;
            this.modify_btn_qd.AllowMouseEffects = true;
            this.modify_btn_qd.AllowToggling = false;
            this.modify_btn_qd.AnimationSpeed = 200;
            this.modify_btn_qd.AutoGenerateColors = false;
            this.modify_btn_qd.AutoRoundBorders = false;
            this.modify_btn_qd.AutoSizeLeftIcon = true;
            this.modify_btn_qd.AutoSizeRightIcon = true;
            this.modify_btn_qd.BackColor = System.Drawing.Color.Transparent;
            this.modify_btn_qd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.modify_btn_qd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("modify_btn_qd.BackgroundImage")));
            this.modify_btn_qd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modify_btn_qd.ButtonText = "Modify";
            this.modify_btn_qd.ButtonTextMarginLeft = 0;
            this.modify_btn_qd.ColorContrastOnClick = 45;
            this.modify_btn_qd.ColorContrastOnHover = 45;
            this.modify_btn_qd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.modify_btn_qd.CustomizableEdges = borderEdges3;
            this.modify_btn_qd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.modify_btn_qd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.modify_btn_qd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modify_btn_qd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.modify_btn_qd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.modify_btn_qd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.modify_btn_qd.ForeColor = System.Drawing.Color.White;
            this.modify_btn_qd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.modify_btn_qd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.modify_btn_qd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.modify_btn_qd.IconMarginLeft = 11;
            this.modify_btn_qd.IconPadding = 10;
            this.modify_btn_qd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.modify_btn_qd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.modify_btn_qd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.modify_btn_qd.IconSize = 25;
            this.modify_btn_qd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.modify_btn_qd.IdleBorderRadius = 1;
            this.modify_btn_qd.IdleBorderThickness = 1;
            this.modify_btn_qd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.modify_btn_qd.IdleIconLeftImage = null;
            this.modify_btn_qd.IdleIconRightImage = null;
            this.modify_btn_qd.IndicateFocus = false;
            this.modify_btn_qd.Location = new System.Drawing.Point(529, 479);
            this.modify_btn_qd.Name = "modify_btn_qd";
            this.modify_btn_qd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.modify_btn_qd.OnDisabledState.BorderRadius = 1;
            this.modify_btn_qd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modify_btn_qd.OnDisabledState.BorderThickness = 1;
            this.modify_btn_qd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modify_btn_qd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.modify_btn_qd.OnDisabledState.IconLeftImage = null;
            this.modify_btn_qd.OnDisabledState.IconRightImage = null;
            this.modify_btn_qd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.modify_btn_qd.onHoverState.BorderRadius = 1;
            this.modify_btn_qd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modify_btn_qd.onHoverState.BorderThickness = 1;
            this.modify_btn_qd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.modify_btn_qd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.modify_btn_qd.onHoverState.IconLeftImage = null;
            this.modify_btn_qd.onHoverState.IconRightImage = null;
            this.modify_btn_qd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.modify_btn_qd.OnIdleState.BorderRadius = 1;
            this.modify_btn_qd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modify_btn_qd.OnIdleState.BorderThickness = 1;
            this.modify_btn_qd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.modify_btn_qd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.modify_btn_qd.OnIdleState.IconLeftImage = null;
            this.modify_btn_qd.OnIdleState.IconRightImage = null;
            this.modify_btn_qd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.modify_btn_qd.OnPressedState.BorderRadius = 1;
            this.modify_btn_qd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modify_btn_qd.OnPressedState.BorderThickness = 1;
            this.modify_btn_qd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.modify_btn_qd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.modify_btn_qd.OnPressedState.IconLeftImage = null;
            this.modify_btn_qd.OnPressedState.IconRightImage = null;
            this.modify_btn_qd.Size = new System.Drawing.Size(159, 39);
            this.modify_btn_qd.TabIndex = 9;
            this.modify_btn_qd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.modify_btn_qd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.modify_btn_qd.TextMarginLeft = 0;
            this.modify_btn_qd.TextPadding = new System.Windows.Forms.Padding(0);
            this.modify_btn_qd.UseDefaultRadiusAndThickness = true;
            this.modify_btn_qd.Click += new System.EventHandler(this.modify_btn_qd_Click);
            // 
            // Save_btn_qd
            // 
            this.Save_btn_qd.AllowAnimations = true;
            this.Save_btn_qd.AllowMouseEffects = true;
            this.Save_btn_qd.AllowToggling = false;
            this.Save_btn_qd.AnimationSpeed = 200;
            this.Save_btn_qd.AutoGenerateColors = false;
            this.Save_btn_qd.AutoRoundBorders = false;
            this.Save_btn_qd.AutoSizeLeftIcon = true;
            this.Save_btn_qd.AutoSizeRightIcon = true;
            this.Save_btn_qd.BackColor = System.Drawing.Color.Transparent;
            this.Save_btn_qd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.Save_btn_qd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Save_btn_qd.BackgroundImage")));
            this.Save_btn_qd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Save_btn_qd.ButtonText = "Save";
            this.Save_btn_qd.ButtonTextMarginLeft = 0;
            this.Save_btn_qd.ColorContrastOnClick = 45;
            this.Save_btn_qd.ColorContrastOnHover = 45;
            this.Save_btn_qd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Save_btn_qd.CustomizableEdges = borderEdges4;
            this.Save_btn_qd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Save_btn_qd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save_btn_qd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save_btn_qd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save_btn_qd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.Save_btn_qd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Save_btn_qd.ForeColor = System.Drawing.Color.White;
            this.Save_btn_qd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Save_btn_qd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Save_btn_qd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Save_btn_qd.IconMarginLeft = 11;
            this.Save_btn_qd.IconPadding = 10;
            this.Save_btn_qd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Save_btn_qd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Save_btn_qd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Save_btn_qd.IconSize = 25;
            this.Save_btn_qd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.Save_btn_qd.IdleBorderRadius = 1;
            this.Save_btn_qd.IdleBorderThickness = 1;
            this.Save_btn_qd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.Save_btn_qd.IdleIconLeftImage = null;
            this.Save_btn_qd.IdleIconRightImage = null;
            this.Save_btn_qd.IndicateFocus = false;
            this.Save_btn_qd.Location = new System.Drawing.Point(529, 534);
            this.Save_btn_qd.Name = "Save_btn_qd";
            this.Save_btn_qd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save_btn_qd.OnDisabledState.BorderRadius = 1;
            this.Save_btn_qd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Save_btn_qd.OnDisabledState.BorderThickness = 1;
            this.Save_btn_qd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save_btn_qd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save_btn_qd.OnDisabledState.IconLeftImage = null;
            this.Save_btn_qd.OnDisabledState.IconRightImage = null;
            this.Save_btn_qd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Save_btn_qd.onHoverState.BorderRadius = 1;
            this.Save_btn_qd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Save_btn_qd.onHoverState.BorderThickness = 1;
            this.Save_btn_qd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Save_btn_qd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Save_btn_qd.onHoverState.IconLeftImage = null;
            this.Save_btn_qd.onHoverState.IconRightImage = null;
            this.Save_btn_qd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Save_btn_qd.OnIdleState.BorderRadius = 1;
            this.Save_btn_qd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Save_btn_qd.OnIdleState.BorderThickness = 1;
            this.Save_btn_qd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.Save_btn_qd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Save_btn_qd.OnIdleState.IconLeftImage = null;
            this.Save_btn_qd.OnIdleState.IconRightImage = null;
            this.Save_btn_qd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Save_btn_qd.OnPressedState.BorderRadius = 1;
            this.Save_btn_qd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Save_btn_qd.OnPressedState.BorderThickness = 1;
            this.Save_btn_qd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Save_btn_qd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Save_btn_qd.OnPressedState.IconLeftImage = null;
            this.Save_btn_qd.OnPressedState.IconRightImage = null;
            this.Save_btn_qd.Size = new System.Drawing.Size(159, 39);
            this.Save_btn_qd.TabIndex = 8;
            this.Save_btn_qd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Save_btn_qd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Save_btn_qd.TextMarginLeft = 0;
            this.Save_btn_qd.TextPadding = new System.Windows.Forms.Padding(0);
            this.Save_btn_qd.UseDefaultRadiusAndThickness = true;
            this.Save_btn_qd.Click += new System.EventHandler(this.Save_btn_qd_Click);
            // 
            // new_btn_qd
            // 
            this.new_btn_qd.AllowAnimations = true;
            this.new_btn_qd.AllowMouseEffects = true;
            this.new_btn_qd.AllowToggling = false;
            this.new_btn_qd.AnimationSpeed = 200;
            this.new_btn_qd.AutoGenerateColors = false;
            this.new_btn_qd.AutoRoundBorders = false;
            this.new_btn_qd.AutoSizeLeftIcon = true;
            this.new_btn_qd.AutoSizeRightIcon = true;
            this.new_btn_qd.BackColor = System.Drawing.Color.Transparent;
            this.new_btn_qd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.new_btn_qd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("new_btn_qd.BackgroundImage")));
            this.new_btn_qd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.new_btn_qd.ButtonText = "New";
            this.new_btn_qd.ButtonTextMarginLeft = 0;
            this.new_btn_qd.ColorContrastOnClick = 45;
            this.new_btn_qd.ColorContrastOnHover = 45;
            this.new_btn_qd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.new_btn_qd.CustomizableEdges = borderEdges5;
            this.new_btn_qd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.new_btn_qd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.new_btn_qd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.new_btn_qd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.new_btn_qd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.new_btn_qd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.new_btn_qd.ForeColor = System.Drawing.Color.White;
            this.new_btn_qd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.new_btn_qd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.new_btn_qd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.new_btn_qd.IconMarginLeft = 11;
            this.new_btn_qd.IconPadding = 10;
            this.new_btn_qd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.new_btn_qd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.new_btn_qd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.new_btn_qd.IconSize = 25;
            this.new_btn_qd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.new_btn_qd.IdleBorderRadius = 1;
            this.new_btn_qd.IdleBorderThickness = 1;
            this.new_btn_qd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.new_btn_qd.IdleIconLeftImage = null;
            this.new_btn_qd.IdleIconRightImage = null;
            this.new_btn_qd.IndicateFocus = false;
            this.new_btn_qd.Location = new System.Drawing.Point(529, 420);
            this.new_btn_qd.Name = "new_btn_qd";
            this.new_btn_qd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.new_btn_qd.OnDisabledState.BorderRadius = 1;
            this.new_btn_qd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.new_btn_qd.OnDisabledState.BorderThickness = 1;
            this.new_btn_qd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.new_btn_qd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.new_btn_qd.OnDisabledState.IconLeftImage = null;
            this.new_btn_qd.OnDisabledState.IconRightImage = null;
            this.new_btn_qd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.new_btn_qd.onHoverState.BorderRadius = 1;
            this.new_btn_qd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.new_btn_qd.onHoverState.BorderThickness = 1;
            this.new_btn_qd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.new_btn_qd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.new_btn_qd.onHoverState.IconLeftImage = null;
            this.new_btn_qd.onHoverState.IconRightImage = null;
            this.new_btn_qd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.new_btn_qd.OnIdleState.BorderRadius = 1;
            this.new_btn_qd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.new_btn_qd.OnIdleState.BorderThickness = 1;
            this.new_btn_qd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.new_btn_qd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.new_btn_qd.OnIdleState.IconLeftImage = null;
            this.new_btn_qd.OnIdleState.IconRightImage = null;
            this.new_btn_qd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.new_btn_qd.OnPressedState.BorderRadius = 1;
            this.new_btn_qd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.new_btn_qd.OnPressedState.BorderThickness = 1;
            this.new_btn_qd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.new_btn_qd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.new_btn_qd.OnPressedState.IconLeftImage = null;
            this.new_btn_qd.OnPressedState.IconRightImage = null;
            this.new_btn_qd.Size = new System.Drawing.Size(159, 39);
            this.new_btn_qd.TabIndex = 7;
            this.new_btn_qd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.new_btn_qd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.new_btn_qd.TextMarginLeft = 0;
            this.new_btn_qd.TextPadding = new System.Windows.Forms.Padding(0);
            this.new_btn_qd.UseDefaultRadiusAndThickness = true;
            this.new_btn_qd.Click += new System.EventHandler(this.new_btn_qd_Click);
            // 
            // bun_addcab_dgv
            // 
            this.bun_addcab_dgv.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bun_addcab_dgv.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bun_addcab_dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bun_addcab_dgv.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bun_addcab_dgv.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bun_addcab_dgv.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bun_addcab_dgv.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bun_addcab_dgv.ColumnHeadersHeight = 40;
            this.bun_addcab_dgv.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.add_cabno,
            this.add_cabmod,
            this.add_cabdet,
            this.add_cabppkm});
            this.bun_addcab_dgv.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bun_addcab_dgv.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bun_addcab_dgv.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bun_addcab_dgv.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bun_addcab_dgv.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bun_addcab_dgv.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bun_addcab_dgv.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bun_addcab_dgv.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bun_addcab_dgv.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bun_addcab_dgv.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bun_addcab_dgv.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bun_addcab_dgv.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bun_addcab_dgv.CurrentTheme.Name = null;
            this.bun_addcab_dgv.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bun_addcab_dgv.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bun_addcab_dgv.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bun_addcab_dgv.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bun_addcab_dgv.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bun_addcab_dgv.DefaultCellStyle = dataGridViewCellStyle3;
            this.bun_addcab_dgv.EnableHeadersVisualStyles = false;
            this.bun_addcab_dgv.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bun_addcab_dgv.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bun_addcab_dgv.HeaderBgColor = System.Drawing.Color.Empty;
            this.bun_addcab_dgv.HeaderForeColor = System.Drawing.Color.White;
            this.bun_addcab_dgv.Location = new System.Drawing.Point(709, 20);
            this.bun_addcab_dgv.Name = "bun_addcab_dgv";
            this.bun_addcab_dgv.ReadOnly = true;
            this.bun_addcab_dgv.RowHeadersVisible = false;
            this.bun_addcab_dgv.RowHeadersWidth = 51;
            this.bun_addcab_dgv.RowTemplate.Height = 40;
            this.bun_addcab_dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bun_addcab_dgv.Size = new System.Drawing.Size(651, 792);
            this.bun_addcab_dgv.TabIndex = 2;
            this.bun_addcab_dgv.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.bun_addcab_dgv.DoubleClick += new System.EventHandler(this.bun_addcab_dgv_DoubleClick);
            // 
            // add_cabno
            // 
            this.add_cabno.DataPropertyName = "cab_reg";
            this.add_cabno.HeaderText = "Cab no";
            this.add_cabno.MinimumWidth = 6;
            this.add_cabno.Name = "add_cabno";
            this.add_cabno.ReadOnly = true;
            // 
            // add_cabmod
            // 
            this.add_cabmod.DataPropertyName = "cab_model";
            this.add_cabmod.HeaderText = "Model";
            this.add_cabmod.MinimumWidth = 6;
            this.add_cabmod.Name = "add_cabmod";
            this.add_cabmod.ReadOnly = true;
            // 
            // add_cabdet
            // 
            this.add_cabdet.DataPropertyName = "cab_desc";
            this.add_cabdet.HeaderText = "Details";
            this.add_cabdet.MinimumWidth = 6;
            this.add_cabdet.Name = "add_cabdet";
            this.add_cabdet.ReadOnly = true;
            // 
            // add_cabppkm
            // 
            this.add_cabppkm.DataPropertyName = "cab_ppkm";
            this.add_cabppkm.HeaderText = "Price/KM";
            this.add_cabppkm.MinimumWidth = 6;
            this.add_cabppkm.Name = "add_cabppkm";
            this.add_cabppkm.ReadOnly = true;
            // 
            // cab
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(20)))), ((int)(((byte)(34)))));
            this.Controls.Add(this.QD_Panel);
            this.Name = "cab";
            this.Size = new System.Drawing.Size(1440, 892);
            this.QD_Panel.ResumeLayout(false);
            this.QD_Panel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bun_addcab_dgv)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel QD_Panel;
        private Bunifu.UI.WinForms.BunifuTextBox bun_addcabppkm_tb;
        private Bunifu.UI.WinForms.BunifuTextBox bun_addcabdet_tb;
        private Bunifu.UI.WinForms.BunifuTextBox bun_addcabnam_tb;
        private Bunifu.UI.WinForms.BunifuTextBox bun_addcabno_tb;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 list_btn_qd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 Delete_btn_qd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 modify_btn_qd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 Save_btn_qd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 new_btn_qd;
        private Bunifu.UI.WinForms.BunifuDataGridView bun_addcab_dgv;
        private System.Windows.Forms.DataGridViewTextBoxColumn add_cabno;
        private System.Windows.Forms.DataGridViewTextBoxColumn add_cabmod;
        private System.Windows.Forms.DataGridViewTextBoxColumn add_cabdet;
        private System.Windows.Forms.DataGridViewTextBoxColumn add_cabppkm;
    }
}
