namespace CabManagement
{
    partial class custdet
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(custdet));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.QD_Panel = new System.Windows.Forms.Panel();
            this.bun_custmail_txb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bun_custph_txb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bun_custadd_txb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bun_custnam_txb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bun_custcode_txb = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.list_btn_qd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.Delete_btn_qd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.modify_btn_qd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.Save_btn_qd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.new_btn_qd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bun_addcust_dgv = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.custcode = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.custname = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.custph = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.custadd = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.custmail = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.QD_Panel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bun_addcust_dgv)).BeginInit();
            this.SuspendLayout();
            // 
            // QD_Panel
            // 
            this.QD_Panel.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(20)))), ((int)(((byte)(28)))));
            this.QD_Panel.Controls.Add(this.bun_custmail_txb);
            this.QD_Panel.Controls.Add(this.bun_custph_txb);
            this.QD_Panel.Controls.Add(this.bun_custadd_txb);
            this.QD_Panel.Controls.Add(this.bun_custnam_txb);
            this.QD_Panel.Controls.Add(this.bun_custcode_txb);
            this.QD_Panel.Controls.Add(this.label6);
            this.QD_Panel.Controls.Add(this.label5);
            this.QD_Panel.Controls.Add(this.label4);
            this.QD_Panel.Controls.Add(this.label1);
            this.QD_Panel.Controls.Add(this.label3);
            this.QD_Panel.Controls.Add(this.label2);
            this.QD_Panel.Controls.Add(this.list_btn_qd);
            this.QD_Panel.Controls.Add(this.Delete_btn_qd);
            this.QD_Panel.Controls.Add(this.modify_btn_qd);
            this.QD_Panel.Controls.Add(this.Save_btn_qd);
            this.QD_Panel.Controls.Add(this.new_btn_qd);
            this.QD_Panel.Controls.Add(this.bun_addcust_dgv);
            this.QD_Panel.Location = new System.Drawing.Point(22, 22);
            this.QD_Panel.Name = "QD_Panel";
            this.QD_Panel.Size = new System.Drawing.Size(1397, 848);
            this.QD_Panel.TabIndex = 8;
            // 
            // bun_custmail_txb
            // 
            this.bun_custmail_txb.AcceptsReturn = false;
            this.bun_custmail_txb.AcceptsTab = false;
            this.bun_custmail_txb.AnimationSpeed = 200;
            this.bun_custmail_txb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bun_custmail_txb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bun_custmail_txb.AutoSizeHeight = true;
            this.bun_custmail_txb.BackColor = System.Drawing.Color.Transparent;
            this.bun_custmail_txb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bun_custmail_txb.BackgroundImage")));
            this.bun_custmail_txb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bun_custmail_txb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bun_custmail_txb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bun_custmail_txb.BorderColorIdle = System.Drawing.Color.Silver;
            this.bun_custmail_txb.BorderRadius = 1;
            this.bun_custmail_txb.BorderThickness = 1;
            this.bun_custmail_txb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bun_custmail_txb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custmail_txb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bun_custmail_txb.DefaultText = "";
            this.bun_custmail_txb.FillColor = System.Drawing.Color.White;
            this.bun_custmail_txb.HideSelection = true;
            this.bun_custmail_txb.IconLeft = null;
            this.bun_custmail_txb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custmail_txb.IconPadding = 10;
            this.bun_custmail_txb.IconRight = null;
            this.bun_custmail_txb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custmail_txb.Lines = new string[0];
            this.bun_custmail_txb.Location = new System.Drawing.Point(195, 427);
            this.bun_custmail_txb.MaxLength = 32767;
            this.bun_custmail_txb.MinimumSize = new System.Drawing.Size(1, 1);
            this.bun_custmail_txb.Modified = false;
            this.bun_custmail_txb.Multiline = false;
            this.bun_custmail_txb.Name = "bun_custmail_txb";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custmail_txb.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bun_custmail_txb.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custmail_txb.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custmail_txb.OnIdleState = stateProperties4;
            this.bun_custmail_txb.Padding = new System.Windows.Forms.Padding(3);
            this.bun_custmail_txb.PasswordChar = '\0';
            this.bun_custmail_txb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bun_custmail_txb.PlaceholderText = "Enter text";
            this.bun_custmail_txb.ReadOnly = false;
            this.bun_custmail_txb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bun_custmail_txb.SelectedText = "";
            this.bun_custmail_txb.SelectionLength = 0;
            this.bun_custmail_txb.SelectionStart = 0;
            this.bun_custmail_txb.ShortcutsEnabled = true;
            this.bun_custmail_txb.Size = new System.Drawing.Size(318, 26);
            this.bun_custmail_txb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bun_custmail_txb.TabIndex = 28;
            this.bun_custmail_txb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bun_custmail_txb.TextMarginBottom = 0;
            this.bun_custmail_txb.TextMarginLeft = 3;
            this.bun_custmail_txb.TextMarginTop = 1;
            this.bun_custmail_txb.TextPlaceholder = "Enter text";
            this.bun_custmail_txb.UseSystemPasswordChar = false;
            this.bun_custmail_txb.WordWrap = true;
            // 
            // bun_custph_txb
            // 
            this.bun_custph_txb.AcceptsReturn = false;
            this.bun_custph_txb.AcceptsTab = false;
            this.bun_custph_txb.AnimationSpeed = 200;
            this.bun_custph_txb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bun_custph_txb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bun_custph_txb.AutoSizeHeight = true;
            this.bun_custph_txb.BackColor = System.Drawing.Color.Transparent;
            this.bun_custph_txb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bun_custph_txb.BackgroundImage")));
            this.bun_custph_txb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bun_custph_txb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bun_custph_txb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bun_custph_txb.BorderColorIdle = System.Drawing.Color.Silver;
            this.bun_custph_txb.BorderRadius = 1;
            this.bun_custph_txb.BorderThickness = 1;
            this.bun_custph_txb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bun_custph_txb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custph_txb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bun_custph_txb.DefaultText = "";
            this.bun_custph_txb.FillColor = System.Drawing.Color.White;
            this.bun_custph_txb.HideSelection = true;
            this.bun_custph_txb.IconLeft = null;
            this.bun_custph_txb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custph_txb.IconPadding = 10;
            this.bun_custph_txb.IconRight = null;
            this.bun_custph_txb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custph_txb.Lines = new string[0];
            this.bun_custph_txb.Location = new System.Drawing.Point(195, 344);
            this.bun_custph_txb.MaxLength = 10;
            this.bun_custph_txb.MinimumSize = new System.Drawing.Size(1, 1);
            this.bun_custph_txb.Modified = false;
            this.bun_custph_txb.Multiline = false;
            this.bun_custph_txb.Name = "bun_custph_txb";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custph_txb.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bun_custph_txb.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custph_txb.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custph_txb.OnIdleState = stateProperties8;
            this.bun_custph_txb.Padding = new System.Windows.Forms.Padding(3);
            this.bun_custph_txb.PasswordChar = '\0';
            this.bun_custph_txb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bun_custph_txb.PlaceholderText = "";
            this.bun_custph_txb.ReadOnly = false;
            this.bun_custph_txb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bun_custph_txb.SelectedText = "";
            this.bun_custph_txb.SelectionLength = 0;
            this.bun_custph_txb.SelectionStart = 0;
            this.bun_custph_txb.ShortcutsEnabled = true;
            this.bun_custph_txb.Size = new System.Drawing.Size(318, 26);
            this.bun_custph_txb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bun_custph_txb.TabIndex = 27;
            this.bun_custph_txb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bun_custph_txb.TextMarginBottom = 0;
            this.bun_custph_txb.TextMarginLeft = 3;
            this.bun_custph_txb.TextMarginTop = 1;
            this.bun_custph_txb.TextPlaceholder = "";
            this.bun_custph_txb.UseSystemPasswordChar = false;
            this.bun_custph_txb.WordWrap = true;
            this.bun_custph_txb.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.bun_custph_txb_KeyPress);
            this.bun_custph_txb.Leave += new System.EventHandler(this.bun_custph_txb_Leave);
            // 
            // bun_custadd_txb
            // 
            this.bun_custadd_txb.AcceptsReturn = false;
            this.bun_custadd_txb.AcceptsTab = false;
            this.bun_custadd_txb.AnimationSpeed = 200;
            this.bun_custadd_txb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bun_custadd_txb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bun_custadd_txb.AutoSizeHeight = true;
            this.bun_custadd_txb.BackColor = System.Drawing.Color.Transparent;
            this.bun_custadd_txb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bun_custadd_txb.BackgroundImage")));
            this.bun_custadd_txb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bun_custadd_txb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bun_custadd_txb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bun_custadd_txb.BorderColorIdle = System.Drawing.Color.Silver;
            this.bun_custadd_txb.BorderRadius = 1;
            this.bun_custadd_txb.BorderThickness = 1;
            this.bun_custadd_txb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bun_custadd_txb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custadd_txb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bun_custadd_txb.DefaultText = "";
            this.bun_custadd_txb.FillColor = System.Drawing.Color.White;
            this.bun_custadd_txb.HideSelection = true;
            this.bun_custadd_txb.IconLeft = null;
            this.bun_custadd_txb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custadd_txb.IconPadding = 10;
            this.bun_custadd_txb.IconRight = null;
            this.bun_custadd_txb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custadd_txb.Lines = new string[0];
            this.bun_custadd_txb.Location = new System.Drawing.Point(195, 236);
            this.bun_custadd_txb.MaxLength = 32767;
            this.bun_custadd_txb.MinimumSize = new System.Drawing.Size(1, 1);
            this.bun_custadd_txb.Modified = false;
            this.bun_custadd_txb.Multiline = false;
            this.bun_custadd_txb.Name = "bun_custadd_txb";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custadd_txb.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bun_custadd_txb.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custadd_txb.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custadd_txb.OnIdleState = stateProperties12;
            this.bun_custadd_txb.Padding = new System.Windows.Forms.Padding(3);
            this.bun_custadd_txb.PasswordChar = '\0';
            this.bun_custadd_txb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bun_custadd_txb.PlaceholderText = "Enter text";
            this.bun_custadd_txb.ReadOnly = false;
            this.bun_custadd_txb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bun_custadd_txb.SelectedText = "";
            this.bun_custadd_txb.SelectionLength = 0;
            this.bun_custadd_txb.SelectionStart = 0;
            this.bun_custadd_txb.ShortcutsEnabled = true;
            this.bun_custadd_txb.Size = new System.Drawing.Size(318, 73);
            this.bun_custadd_txb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bun_custadd_txb.TabIndex = 26;
            this.bun_custadd_txb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bun_custadd_txb.TextMarginBottom = 0;
            this.bun_custadd_txb.TextMarginLeft = 3;
            this.bun_custadd_txb.TextMarginTop = 1;
            this.bun_custadd_txb.TextPlaceholder = "Enter text";
            this.bun_custadd_txb.UseSystemPasswordChar = false;
            this.bun_custadd_txb.WordWrap = true;
            // 
            // bun_custnam_txb
            // 
            this.bun_custnam_txb.AcceptsReturn = false;
            this.bun_custnam_txb.AcceptsTab = false;
            this.bun_custnam_txb.AnimationSpeed = 200;
            this.bun_custnam_txb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bun_custnam_txb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bun_custnam_txb.AutoSizeHeight = true;
            this.bun_custnam_txb.BackColor = System.Drawing.Color.Transparent;
            this.bun_custnam_txb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bun_custnam_txb.BackgroundImage")));
            this.bun_custnam_txb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bun_custnam_txb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bun_custnam_txb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bun_custnam_txb.BorderColorIdle = System.Drawing.Color.Silver;
            this.bun_custnam_txb.BorderRadius = 1;
            this.bun_custnam_txb.BorderThickness = 1;
            this.bun_custnam_txb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bun_custnam_txb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custnam_txb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bun_custnam_txb.DefaultText = "";
            this.bun_custnam_txb.FillColor = System.Drawing.Color.White;
            this.bun_custnam_txb.HideSelection = true;
            this.bun_custnam_txb.IconLeft = null;
            this.bun_custnam_txb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custnam_txb.IconPadding = 10;
            this.bun_custnam_txb.IconRight = null;
            this.bun_custnam_txb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custnam_txb.Lines = new string[0];
            this.bun_custnam_txb.Location = new System.Drawing.Point(195, 167);
            this.bun_custnam_txb.MaxLength = 32767;
            this.bun_custnam_txb.MinimumSize = new System.Drawing.Size(1, 1);
            this.bun_custnam_txb.Modified = false;
            this.bun_custnam_txb.Multiline = false;
            this.bun_custnam_txb.Name = "bun_custnam_txb";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custnam_txb.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bun_custnam_txb.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custnam_txb.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custnam_txb.OnIdleState = stateProperties16;
            this.bun_custnam_txb.Padding = new System.Windows.Forms.Padding(3);
            this.bun_custnam_txb.PasswordChar = '\0';
            this.bun_custnam_txb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bun_custnam_txb.PlaceholderText = "Enter text";
            this.bun_custnam_txb.ReadOnly = false;
            this.bun_custnam_txb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bun_custnam_txb.SelectedText = "";
            this.bun_custnam_txb.SelectionLength = 0;
            this.bun_custnam_txb.SelectionStart = 0;
            this.bun_custnam_txb.ShortcutsEnabled = true;
            this.bun_custnam_txb.Size = new System.Drawing.Size(318, 26);
            this.bun_custnam_txb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bun_custnam_txb.TabIndex = 25;
            this.bun_custnam_txb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bun_custnam_txb.TextMarginBottom = 0;
            this.bun_custnam_txb.TextMarginLeft = 3;
            this.bun_custnam_txb.TextMarginTop = 1;
            this.bun_custnam_txb.TextPlaceholder = "Enter text";
            this.bun_custnam_txb.UseSystemPasswordChar = false;
            this.bun_custnam_txb.WordWrap = true;
            // 
            // bun_custcode_txb
            // 
            this.bun_custcode_txb.AcceptsReturn = false;
            this.bun_custcode_txb.AcceptsTab = false;
            this.bun_custcode_txb.AnimationSpeed = 200;
            this.bun_custcode_txb.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bun_custcode_txb.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bun_custcode_txb.AutoSizeHeight = true;
            this.bun_custcode_txb.BackColor = System.Drawing.Color.Transparent;
            this.bun_custcode_txb.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bun_custcode_txb.BackgroundImage")));
            this.bun_custcode_txb.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bun_custcode_txb.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bun_custcode_txb.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bun_custcode_txb.BorderColorIdle = System.Drawing.Color.Silver;
            this.bun_custcode_txb.BorderRadius = 1;
            this.bun_custcode_txb.BorderThickness = 1;
            this.bun_custcode_txb.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bun_custcode_txb.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custcode_txb.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bun_custcode_txb.DefaultText = "";
            this.bun_custcode_txb.FillColor = System.Drawing.Color.White;
            this.bun_custcode_txb.HideSelection = true;
            this.bun_custcode_txb.IconLeft = null;
            this.bun_custcode_txb.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custcode_txb.IconPadding = 10;
            this.bun_custcode_txb.IconRight = null;
            this.bun_custcode_txb.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bun_custcode_txb.Lines = new string[0];
            this.bun_custcode_txb.Location = new System.Drawing.Point(195, 102);
            this.bun_custcode_txb.MaxLength = 32767;
            this.bun_custcode_txb.MinimumSize = new System.Drawing.Size(1, 1);
            this.bun_custcode_txb.Modified = false;
            this.bun_custcode_txb.Multiline = false;
            this.bun_custcode_txb.Name = "bun_custcode_txb";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custcode_txb.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bun_custcode_txb.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custcode_txb.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bun_custcode_txb.OnIdleState = stateProperties20;
            this.bun_custcode_txb.Padding = new System.Windows.Forms.Padding(3);
            this.bun_custcode_txb.PasswordChar = '\0';
            this.bun_custcode_txb.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bun_custcode_txb.PlaceholderText = "Enter text";
            this.bun_custcode_txb.ReadOnly = false;
            this.bun_custcode_txb.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bun_custcode_txb.SelectedText = "";
            this.bun_custcode_txb.SelectionLength = 0;
            this.bun_custcode_txb.SelectionStart = 0;
            this.bun_custcode_txb.ShortcutsEnabled = true;
            this.bun_custcode_txb.Size = new System.Drawing.Size(318, 26);
            this.bun_custcode_txb.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bun_custcode_txb.TabIndex = 24;
            this.bun_custcode_txb.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bun_custcode_txb.TextMarginBottom = 0;
            this.bun_custcode_txb.TextMarginLeft = 3;
            this.bun_custcode_txb.TextMarginTop = 1;
            this.bun_custcode_txb.TextPlaceholder = "Enter text";
            this.bun_custcode_txb.UseSystemPasswordChar = false;
            this.bun_custcode_txb.WordWrap = true;
            this.bun_custcode_txb.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.bun_custcode_txb_KeyPress);
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.BackColor = System.Drawing.Color.Transparent;
            this.label6.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.White;
            this.label6.Location = new System.Drawing.Point(36, 432);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(56, 22);
            this.label6.TabIndex = 19;
            this.label6.Text = "Email";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.BackColor = System.Drawing.Color.Transparent;
            this.label5.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.White;
            this.label5.Location = new System.Drawing.Point(37, 349);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(69, 22);
            this.label5.TabIndex = 18;
            this.label5.Text = "Phone";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.White;
            this.label4.Location = new System.Drawing.Point(36, 236);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(83, 22);
            this.label4.TabIndex = 17;
            this.label4.Text = "Address";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(24, 167);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(159, 22);
            this.label1.TabIndex = 16;
            this.label1.Text = "Customer Name";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Century Gothic", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.White;
            this.label3.Location = new System.Drawing.Point(24, 102);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(155, 22);
            this.label3.TabIndex = 15;
            this.label3.Text = "Customer Code";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Century Gothic", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.White;
            this.label2.Location = new System.Drawing.Point(269, 20);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(216, 30);
            this.label2.TabIndex = 14;
            this.label2.Text = "Customer Details";
            // 
            // list_btn_qd
            // 
            this.list_btn_qd.AllowAnimations = true;
            this.list_btn_qd.AllowMouseEffects = true;
            this.list_btn_qd.AllowToggling = false;
            this.list_btn_qd.AnimationSpeed = 200;
            this.list_btn_qd.AutoGenerateColors = false;
            this.list_btn_qd.AutoRoundBorders = false;
            this.list_btn_qd.AutoSizeLeftIcon = true;
            this.list_btn_qd.AutoSizeRightIcon = true;
            this.list_btn_qd.BackColor = System.Drawing.Color.Transparent;
            this.list_btn_qd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.list_btn_qd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("list_btn_qd.BackgroundImage")));
            this.list_btn_qd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.list_btn_qd.ButtonText = "List";
            this.list_btn_qd.ButtonTextMarginLeft = 0;
            this.list_btn_qd.ColorContrastOnClick = 45;
            this.list_btn_qd.ColorContrastOnHover = 45;
            this.list_btn_qd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.list_btn_qd.CustomizableEdges = borderEdges1;
            this.list_btn_qd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.list_btn_qd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.list_btn_qd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.list_btn_qd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.list_btn_qd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.list_btn_qd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.list_btn_qd.ForeColor = System.Drawing.Color.White;
            this.list_btn_qd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.list_btn_qd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.list_btn_qd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.list_btn_qd.IconMarginLeft = 11;
            this.list_btn_qd.IconPadding = 10;
            this.list_btn_qd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.list_btn_qd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.list_btn_qd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.list_btn_qd.IconSize = 25;
            this.list_btn_qd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.list_btn_qd.IdleBorderRadius = 1;
            this.list_btn_qd.IdleBorderThickness = 1;
            this.list_btn_qd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.list_btn_qd.IdleIconLeftImage = null;
            this.list_btn_qd.IdleIconRightImage = null;
            this.list_btn_qd.IndicateFocus = false;
            this.list_btn_qd.Location = new System.Drawing.Point(542, 660);
            this.list_btn_qd.Name = "list_btn_qd";
            this.list_btn_qd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.list_btn_qd.OnDisabledState.BorderRadius = 1;
            this.list_btn_qd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.list_btn_qd.OnDisabledState.BorderThickness = 1;
            this.list_btn_qd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.list_btn_qd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.list_btn_qd.OnDisabledState.IconLeftImage = null;
            this.list_btn_qd.OnDisabledState.IconRightImage = null;
            this.list_btn_qd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.list_btn_qd.onHoverState.BorderRadius = 1;
            this.list_btn_qd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.list_btn_qd.onHoverState.BorderThickness = 1;
            this.list_btn_qd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.list_btn_qd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.list_btn_qd.onHoverState.IconLeftImage = null;
            this.list_btn_qd.onHoverState.IconRightImage = null;
            this.list_btn_qd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.list_btn_qd.OnIdleState.BorderRadius = 1;
            this.list_btn_qd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.list_btn_qd.OnIdleState.BorderThickness = 1;
            this.list_btn_qd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.list_btn_qd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.list_btn_qd.OnIdleState.IconLeftImage = null;
            this.list_btn_qd.OnIdleState.IconRightImage = null;
            this.list_btn_qd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.list_btn_qd.OnPressedState.BorderRadius = 1;
            this.list_btn_qd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.list_btn_qd.OnPressedState.BorderThickness = 1;
            this.list_btn_qd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.list_btn_qd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.list_btn_qd.OnPressedState.IconLeftImage = null;
            this.list_btn_qd.OnPressedState.IconRightImage = null;
            this.list_btn_qd.Size = new System.Drawing.Size(159, 39);
            this.list_btn_qd.TabIndex = 11;
            this.list_btn_qd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.list_btn_qd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.list_btn_qd.TextMarginLeft = 0;
            this.list_btn_qd.TextPadding = new System.Windows.Forms.Padding(0);
            this.list_btn_qd.UseDefaultRadiusAndThickness = true;
            this.list_btn_qd.Click += new System.EventHandler(this.list_btn_qd_Click);
            // 
            // Delete_btn_qd
            // 
            this.Delete_btn_qd.AllowAnimations = true;
            this.Delete_btn_qd.AllowMouseEffects = true;
            this.Delete_btn_qd.AllowToggling = false;
            this.Delete_btn_qd.AnimationSpeed = 200;
            this.Delete_btn_qd.AutoGenerateColors = false;
            this.Delete_btn_qd.AutoRoundBorders = false;
            this.Delete_btn_qd.AutoSizeLeftIcon = true;
            this.Delete_btn_qd.AutoSizeRightIcon = true;
            this.Delete_btn_qd.BackColor = System.Drawing.Color.Transparent;
            this.Delete_btn_qd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.Delete_btn_qd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Delete_btn_qd.BackgroundImage")));
            this.Delete_btn_qd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Delete_btn_qd.ButtonText = "Delete";
            this.Delete_btn_qd.ButtonTextMarginLeft = 0;
            this.Delete_btn_qd.ColorContrastOnClick = 45;
            this.Delete_btn_qd.ColorContrastOnHover = 45;
            this.Delete_btn_qd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Delete_btn_qd.CustomizableEdges = borderEdges2;
            this.Delete_btn_qd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Delete_btn_qd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Delete_btn_qd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Delete_btn_qd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Delete_btn_qd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.Delete_btn_qd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Delete_btn_qd.ForeColor = System.Drawing.Color.White;
            this.Delete_btn_qd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Delete_btn_qd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Delete_btn_qd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Delete_btn_qd.IconMarginLeft = 11;
            this.Delete_btn_qd.IconPadding = 10;
            this.Delete_btn_qd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Delete_btn_qd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Delete_btn_qd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Delete_btn_qd.IconSize = 25;
            this.Delete_btn_qd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.Delete_btn_qd.IdleBorderRadius = 1;
            this.Delete_btn_qd.IdleBorderThickness = 1;
            this.Delete_btn_qd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.Delete_btn_qd.IdleIconLeftImage = null;
            this.Delete_btn_qd.IdleIconRightImage = null;
            this.Delete_btn_qd.IndicateFocus = false;
            this.Delete_btn_qd.Location = new System.Drawing.Point(542, 600);
            this.Delete_btn_qd.Name = "Delete_btn_qd";
            this.Delete_btn_qd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Delete_btn_qd.OnDisabledState.BorderRadius = 1;
            this.Delete_btn_qd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Delete_btn_qd.OnDisabledState.BorderThickness = 1;
            this.Delete_btn_qd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Delete_btn_qd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Delete_btn_qd.OnDisabledState.IconLeftImage = null;
            this.Delete_btn_qd.OnDisabledState.IconRightImage = null;
            this.Delete_btn_qd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Delete_btn_qd.onHoverState.BorderRadius = 1;
            this.Delete_btn_qd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Delete_btn_qd.onHoverState.BorderThickness = 1;
            this.Delete_btn_qd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Delete_btn_qd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Delete_btn_qd.onHoverState.IconLeftImage = null;
            this.Delete_btn_qd.onHoverState.IconRightImage = null;
            this.Delete_btn_qd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Delete_btn_qd.OnIdleState.BorderRadius = 1;
            this.Delete_btn_qd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Delete_btn_qd.OnIdleState.BorderThickness = 1;
            this.Delete_btn_qd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.Delete_btn_qd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Delete_btn_qd.OnIdleState.IconLeftImage = null;
            this.Delete_btn_qd.OnIdleState.IconRightImage = null;
            this.Delete_btn_qd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Delete_btn_qd.OnPressedState.BorderRadius = 1;
            this.Delete_btn_qd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Delete_btn_qd.OnPressedState.BorderThickness = 1;
            this.Delete_btn_qd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Delete_btn_qd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Delete_btn_qd.OnPressedState.IconLeftImage = null;
            this.Delete_btn_qd.OnPressedState.IconRightImage = null;
            this.Delete_btn_qd.Size = new System.Drawing.Size(159, 39);
            this.Delete_btn_qd.TabIndex = 10;
            this.Delete_btn_qd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Delete_btn_qd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Delete_btn_qd.TextMarginLeft = 0;
            this.Delete_btn_qd.TextPadding = new System.Windows.Forms.Padding(0);
            this.Delete_btn_qd.UseDefaultRadiusAndThickness = true;
            this.Delete_btn_qd.Click += new System.EventHandler(this.Delete_btn_qd_Click);
            // 
            // modify_btn_qd
            // 
            this.modify_btn_qd.AllowAnimations = true;
            this.modify_btn_qd.AllowMouseEffects = true;
            this.modify_btn_qd.AllowToggling = false;
            this.modify_btn_qd.AnimationSpeed = 200;
            this.modify_btn_qd.AutoGenerateColors = false;
            this.modify_btn_qd.AutoRoundBorders = false;
            this.modify_btn_qd.AutoSizeLeftIcon = true;
            this.modify_btn_qd.AutoSizeRightIcon = true;
            this.modify_btn_qd.BackColor = System.Drawing.Color.Transparent;
            this.modify_btn_qd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.modify_btn_qd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("modify_btn_qd.BackgroundImage")));
            this.modify_btn_qd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modify_btn_qd.ButtonText = "Modify";
            this.modify_btn_qd.ButtonTextMarginLeft = 0;
            this.modify_btn_qd.ColorContrastOnClick = 45;
            this.modify_btn_qd.ColorContrastOnHover = 45;
            this.modify_btn_qd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.modify_btn_qd.CustomizableEdges = borderEdges3;
            this.modify_btn_qd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.modify_btn_qd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.modify_btn_qd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modify_btn_qd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.modify_btn_qd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.modify_btn_qd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.modify_btn_qd.ForeColor = System.Drawing.Color.White;
            this.modify_btn_qd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.modify_btn_qd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.modify_btn_qd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.modify_btn_qd.IconMarginLeft = 11;
            this.modify_btn_qd.IconPadding = 10;
            this.modify_btn_qd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.modify_btn_qd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.modify_btn_qd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.modify_btn_qd.IconSize = 25;
            this.modify_btn_qd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.modify_btn_qd.IdleBorderRadius = 1;
            this.modify_btn_qd.IdleBorderThickness = 1;
            this.modify_btn_qd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.modify_btn_qd.IdleIconLeftImage = null;
            this.modify_btn_qd.IdleIconRightImage = null;
            this.modify_btn_qd.IndicateFocus = false;
            this.modify_btn_qd.Location = new System.Drawing.Point(542, 486);
            this.modify_btn_qd.Name = "modify_btn_qd";
            this.modify_btn_qd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.modify_btn_qd.OnDisabledState.BorderRadius = 1;
            this.modify_btn_qd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modify_btn_qd.OnDisabledState.BorderThickness = 1;
            this.modify_btn_qd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.modify_btn_qd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.modify_btn_qd.OnDisabledState.IconLeftImage = null;
            this.modify_btn_qd.OnDisabledState.IconRightImage = null;
            this.modify_btn_qd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.modify_btn_qd.onHoverState.BorderRadius = 1;
            this.modify_btn_qd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modify_btn_qd.onHoverState.BorderThickness = 1;
            this.modify_btn_qd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.modify_btn_qd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.modify_btn_qd.onHoverState.IconLeftImage = null;
            this.modify_btn_qd.onHoverState.IconRightImage = null;
            this.modify_btn_qd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.modify_btn_qd.OnIdleState.BorderRadius = 1;
            this.modify_btn_qd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modify_btn_qd.OnIdleState.BorderThickness = 1;
            this.modify_btn_qd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.modify_btn_qd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.modify_btn_qd.OnIdleState.IconLeftImage = null;
            this.modify_btn_qd.OnIdleState.IconRightImage = null;
            this.modify_btn_qd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.modify_btn_qd.OnPressedState.BorderRadius = 1;
            this.modify_btn_qd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.modify_btn_qd.OnPressedState.BorderThickness = 1;
            this.modify_btn_qd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.modify_btn_qd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.modify_btn_qd.OnPressedState.IconLeftImage = null;
            this.modify_btn_qd.OnPressedState.IconRightImage = null;
            this.modify_btn_qd.Size = new System.Drawing.Size(159, 39);
            this.modify_btn_qd.TabIndex = 9;
            this.modify_btn_qd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.modify_btn_qd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.modify_btn_qd.TextMarginLeft = 0;
            this.modify_btn_qd.TextPadding = new System.Windows.Forms.Padding(0);
            this.modify_btn_qd.UseDefaultRadiusAndThickness = true;
            this.modify_btn_qd.Click += new System.EventHandler(this.modify_btn_qd_Click);
            // 
            // Save_btn_qd
            // 
            this.Save_btn_qd.AllowAnimations = true;
            this.Save_btn_qd.AllowMouseEffects = true;
            this.Save_btn_qd.AllowToggling = false;
            this.Save_btn_qd.AnimationSpeed = 200;
            this.Save_btn_qd.AutoGenerateColors = false;
            this.Save_btn_qd.AutoRoundBorders = false;
            this.Save_btn_qd.AutoSizeLeftIcon = true;
            this.Save_btn_qd.AutoSizeRightIcon = true;
            this.Save_btn_qd.BackColor = System.Drawing.Color.Transparent;
            this.Save_btn_qd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.Save_btn_qd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Save_btn_qd.BackgroundImage")));
            this.Save_btn_qd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Save_btn_qd.ButtonText = "Save";
            this.Save_btn_qd.ButtonTextMarginLeft = 0;
            this.Save_btn_qd.ColorContrastOnClick = 45;
            this.Save_btn_qd.ColorContrastOnHover = 45;
            this.Save_btn_qd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Save_btn_qd.CustomizableEdges = borderEdges4;
            this.Save_btn_qd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Save_btn_qd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save_btn_qd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save_btn_qd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save_btn_qd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.Save_btn_qd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Save_btn_qd.ForeColor = System.Drawing.Color.White;
            this.Save_btn_qd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Save_btn_qd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Save_btn_qd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Save_btn_qd.IconMarginLeft = 11;
            this.Save_btn_qd.IconPadding = 10;
            this.Save_btn_qd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Save_btn_qd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Save_btn_qd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Save_btn_qd.IconSize = 25;
            this.Save_btn_qd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.Save_btn_qd.IdleBorderRadius = 1;
            this.Save_btn_qd.IdleBorderThickness = 1;
            this.Save_btn_qd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.Save_btn_qd.IdleIconLeftImage = null;
            this.Save_btn_qd.IdleIconRightImage = null;
            this.Save_btn_qd.IndicateFocus = false;
            this.Save_btn_qd.Location = new System.Drawing.Point(542, 541);
            this.Save_btn_qd.Name = "Save_btn_qd";
            this.Save_btn_qd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Save_btn_qd.OnDisabledState.BorderRadius = 1;
            this.Save_btn_qd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Save_btn_qd.OnDisabledState.BorderThickness = 1;
            this.Save_btn_qd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Save_btn_qd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Save_btn_qd.OnDisabledState.IconLeftImage = null;
            this.Save_btn_qd.OnDisabledState.IconRightImage = null;
            this.Save_btn_qd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Save_btn_qd.onHoverState.BorderRadius = 1;
            this.Save_btn_qd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Save_btn_qd.onHoverState.BorderThickness = 1;
            this.Save_btn_qd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Save_btn_qd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Save_btn_qd.onHoverState.IconLeftImage = null;
            this.Save_btn_qd.onHoverState.IconRightImage = null;
            this.Save_btn_qd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.Save_btn_qd.OnIdleState.BorderRadius = 1;
            this.Save_btn_qd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Save_btn_qd.OnIdleState.BorderThickness = 1;
            this.Save_btn_qd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.Save_btn_qd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Save_btn_qd.OnIdleState.IconLeftImage = null;
            this.Save_btn_qd.OnIdleState.IconRightImage = null;
            this.Save_btn_qd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Save_btn_qd.OnPressedState.BorderRadius = 1;
            this.Save_btn_qd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Save_btn_qd.OnPressedState.BorderThickness = 1;
            this.Save_btn_qd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Save_btn_qd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Save_btn_qd.OnPressedState.IconLeftImage = null;
            this.Save_btn_qd.OnPressedState.IconRightImage = null;
            this.Save_btn_qd.Size = new System.Drawing.Size(159, 39);
            this.Save_btn_qd.TabIndex = 8;
            this.Save_btn_qd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Save_btn_qd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Save_btn_qd.TextMarginLeft = 0;
            this.Save_btn_qd.TextPadding = new System.Windows.Forms.Padding(0);
            this.Save_btn_qd.UseDefaultRadiusAndThickness = true;
            this.Save_btn_qd.Click += new System.EventHandler(this.Save_btn_qd_Click);
            // 
            // new_btn_qd
            // 
            this.new_btn_qd.AllowAnimations = true;
            this.new_btn_qd.AllowMouseEffects = true;
            this.new_btn_qd.AllowToggling = false;
            this.new_btn_qd.AnimationSpeed = 200;
            this.new_btn_qd.AutoGenerateColors = false;
            this.new_btn_qd.AutoRoundBorders = false;
            this.new_btn_qd.AutoSizeLeftIcon = true;
            this.new_btn_qd.AutoSizeRightIcon = true;
            this.new_btn_qd.BackColor = System.Drawing.Color.Transparent;
            this.new_btn_qd.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.new_btn_qd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("new_btn_qd.BackgroundImage")));
            this.new_btn_qd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.new_btn_qd.ButtonText = "New";
            this.new_btn_qd.ButtonTextMarginLeft = 0;
            this.new_btn_qd.ColorContrastOnClick = 45;
            this.new_btn_qd.ColorContrastOnHover = 45;
            this.new_btn_qd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.new_btn_qd.CustomizableEdges = borderEdges5;
            this.new_btn_qd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.new_btn_qd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.new_btn_qd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.new_btn_qd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.new_btn_qd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.new_btn_qd.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.new_btn_qd.ForeColor = System.Drawing.Color.White;
            this.new_btn_qd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.new_btn_qd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.new_btn_qd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.new_btn_qd.IconMarginLeft = 11;
            this.new_btn_qd.IconPadding = 10;
            this.new_btn_qd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.new_btn_qd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.new_btn_qd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.new_btn_qd.IconSize = 25;
            this.new_btn_qd.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.new_btn_qd.IdleBorderRadius = 1;
            this.new_btn_qd.IdleBorderThickness = 1;
            this.new_btn_qd.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.new_btn_qd.IdleIconLeftImage = null;
            this.new_btn_qd.IdleIconRightImage = null;
            this.new_btn_qd.IndicateFocus = false;
            this.new_btn_qd.Location = new System.Drawing.Point(542, 427);
            this.new_btn_qd.Name = "new_btn_qd";
            this.new_btn_qd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.new_btn_qd.OnDisabledState.BorderRadius = 1;
            this.new_btn_qd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.new_btn_qd.OnDisabledState.BorderThickness = 1;
            this.new_btn_qd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.new_btn_qd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.new_btn_qd.OnDisabledState.IconLeftImage = null;
            this.new_btn_qd.OnDisabledState.IconRightImage = null;
            this.new_btn_qd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.new_btn_qd.onHoverState.BorderRadius = 1;
            this.new_btn_qd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.new_btn_qd.onHoverState.BorderThickness = 1;
            this.new_btn_qd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.new_btn_qd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.new_btn_qd.onHoverState.IconLeftImage = null;
            this.new_btn_qd.onHoverState.IconRightImage = null;
            this.new_btn_qd.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.new_btn_qd.OnIdleState.BorderRadius = 1;
            this.new_btn_qd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.new_btn_qd.OnIdleState.BorderThickness = 1;
            this.new_btn_qd.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.new_btn_qd.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.new_btn_qd.OnIdleState.IconLeftImage = null;
            this.new_btn_qd.OnIdleState.IconRightImage = null;
            this.new_btn_qd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.new_btn_qd.OnPressedState.BorderRadius = 1;
            this.new_btn_qd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.new_btn_qd.OnPressedState.BorderThickness = 1;
            this.new_btn_qd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.new_btn_qd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.new_btn_qd.OnPressedState.IconLeftImage = null;
            this.new_btn_qd.OnPressedState.IconRightImage = null;
            this.new_btn_qd.Size = new System.Drawing.Size(159, 39);
            this.new_btn_qd.TabIndex = 7;
            this.new_btn_qd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.new_btn_qd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.new_btn_qd.TextMarginLeft = 0;
            this.new_btn_qd.TextPadding = new System.Windows.Forms.Padding(0);
            this.new_btn_qd.UseDefaultRadiusAndThickness = true;
            this.new_btn_qd.Click += new System.EventHandler(this.new_btn_qd_Click);
            // 
            // bun_addcust_dgv
            // 
            this.bun_addcust_dgv.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bun_addcust_dgv.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bun_addcust_dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bun_addcust_dgv.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bun_addcust_dgv.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bun_addcust_dgv.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bun_addcust_dgv.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bun_addcust_dgv.ColumnHeadersHeight = 40;
            this.bun_addcust_dgv.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.custcode,
            this.custname,
            this.custph,
            this.custadd,
            this.custmail});
            this.bun_addcust_dgv.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bun_addcust_dgv.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bun_addcust_dgv.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bun_addcust_dgv.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bun_addcust_dgv.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bun_addcust_dgv.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bun_addcust_dgv.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bun_addcust_dgv.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bun_addcust_dgv.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bun_addcust_dgv.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bun_addcust_dgv.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bun_addcust_dgv.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bun_addcust_dgv.CurrentTheme.Name = null;
            this.bun_addcust_dgv.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bun_addcust_dgv.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bun_addcust_dgv.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bun_addcust_dgv.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bun_addcust_dgv.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bun_addcust_dgv.DefaultCellStyle = dataGridViewCellStyle3;
            this.bun_addcust_dgv.EnableHeadersVisualStyles = false;
            this.bun_addcust_dgv.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bun_addcust_dgv.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bun_addcust_dgv.HeaderBgColor = System.Drawing.Color.Empty;
            this.bun_addcust_dgv.HeaderForeColor = System.Drawing.Color.White;
            this.bun_addcust_dgv.Location = new System.Drawing.Point(727, 20);
            this.bun_addcust_dgv.Name = "bun_addcust_dgv";
            this.bun_addcust_dgv.ReadOnly = true;
            this.bun_addcust_dgv.RowHeadersVisible = false;
            this.bun_addcust_dgv.RowHeadersWidth = 51;
            this.bun_addcust_dgv.RowTemplate.Height = 40;
            this.bun_addcust_dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bun_addcust_dgv.Size = new System.Drawing.Size(651, 792);
            this.bun_addcust_dgv.TabIndex = 2;
            this.bun_addcust_dgv.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.bun_addcust_dgv.DoubleClick += new System.EventHandler(this.bun_addcust_dgv_DoubleClick);
            // 
            // custcode
            // 
            this.custcode.DataPropertyName = "custcode";
            this.custcode.HeaderText = "Cust code";
            this.custcode.MinimumWidth = 6;
            this.custcode.Name = "custcode";
            this.custcode.ReadOnly = true;
            // 
            // custname
            // 
            this.custname.DataPropertyName = "custname";
            this.custname.HeaderText = "Customer Name";
            this.custname.MinimumWidth = 6;
            this.custname.Name = "custname";
            this.custname.ReadOnly = true;
            // 
            // custph
            // 
            this.custph.DataPropertyName = "cust_phno";
            this.custph.HeaderText = "Phone-No";
            this.custph.MinimumWidth = 6;
            this.custph.Name = "custph";
            this.custph.ReadOnly = true;
            // 
            // custadd
            // 
            this.custadd.DataPropertyName = "custadd";
            this.custadd.HeaderText = "address";
            this.custadd.MinimumWidth = 6;
            this.custadd.Name = "custadd";
            this.custadd.ReadOnly = true;
            // 
            // custmail
            // 
            this.custmail.DataPropertyName = "custmail";
            this.custmail.HeaderText = "Mail-ID";
            this.custmail.MinimumWidth = 6;
            this.custmail.Name = "custmail";
            this.custmail.ReadOnly = true;
            // 
            // custdet
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(20)))), ((int)(((byte)(34)))));
            this.Controls.Add(this.QD_Panel);
            this.Name = "custdet";
            this.Size = new System.Drawing.Size(1440, 892);
            this.QD_Panel.ResumeLayout(false);
            this.QD_Panel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bun_addcust_dgv)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel QD_Panel;
        private Bunifu.UI.WinForms.BunifuTextBox bun_custmail_txb;
        private Bunifu.UI.WinForms.BunifuTextBox bun_custph_txb;
        private Bunifu.UI.WinForms.BunifuTextBox bun_custadd_txb;
        private Bunifu.UI.WinForms.BunifuTextBox bun_custnam_txb;
        private Bunifu.UI.WinForms.BunifuTextBox bun_custcode_txb;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 list_btn_qd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 Delete_btn_qd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 modify_btn_qd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 Save_btn_qd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 new_btn_qd;
        private Bunifu.UI.WinForms.BunifuDataGridView bun_addcust_dgv;
        private System.Windows.Forms.DataGridViewTextBoxColumn custcode;
        private System.Windows.Forms.DataGridViewTextBoxColumn custname;
        private System.Windows.Forms.DataGridViewTextBoxColumn custph;
        private System.Windows.Forms.DataGridViewTextBoxColumn custadd;
        private System.Windows.Forms.DataGridViewTextBoxColumn custmail;
    }
}
